language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:
  - 'cd frontend'
  - 'npm install -g bower grunt-cli'
  - 'npm install'
  - 'bower install'
# command to run tests
script:
  - 'cd ..'
  - 'python manage.py test'
  - 'cd frontend'
  - 'grunt test'
